source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Riffle_Example', :exclusive => true do
  pod "Riffle", :path => "../"
end

target 'Riffle_Tests', :exclusive => true do
  pod "Riffle", :path => "../"
end
