source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Riffle_Example', :exclusive => true do
    platform :ios, '9.0'
  pod "Riffle", :path => "../"
end

target 'Riffle_Tests', :exclusive => true do
  pod "Riffle", :path => "../"
end

target 'Riffle_Backend', :exclusive => true do
    platform :osx, '10.10'
   pod "Riffle", :path => "../"
end
