use_frameworks!

target :ExisiOSBackend do
    platform :ios, '9.0'
    pod "Riffle", :path => "../iosRiffle"
end

target :Backend do
    platform :osx, '10.11'
    pod 'Riffle', :path => "../iosRiffle"
end