/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __Hello__
#define __Hello__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jlong JNICALL Java_Hello_multiply (JNIEnv *env, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif

#endif /* __Hello__ */
