# Tell cocoapods what kind of application we're making
platform :ios, '9.0'

# Required when libraries have swift code in them 
use_frameworks!

# The dependency we want to use. You can add more here if you'd like!
pod 'Riffle', :path => "../iosRiffle/"