#!/bin/bash

# Create a temp html file
cat >browser.html <<EOF
<html>
<body>
    <div id="results"></div>
    <script>

EOF

# Drop in the jsriffle lib to make it easy
cat ./jsRiffle.js >> browser.html

# End the jsriffle lib...
cat >>browser.html <<EOF

</script>

EOF

# Drop in our testing code and end the html!
cat >>browser.html <<EOF
<script>
    //This code was generated by Exis/arbiter/repler/browser-generate.sh
    // Overwrite console.log b/c its easier to do selenium testing by looking for element id's then log statements
    console.log = function(s) {
        document.getElementById("results").innerHTML = s;
    };
    var riffle = jsRiffle;
    riffle.setFabric("$WS_URL");
    $EXIS_SETUP

    var app = riffle.Domain("$DOMAIN");
    var backend = app.subdomain("example");
    var client = app.subdomain("example");

    backend.onJoin = function() {
        $EXIS_REPL_CODE
    };

    backend.join()
</script>
</body>
</html>
EOF
