// Objective-C API for talking to github.com/exis-io/core/androidMantle Go package.
//   gobind -lang=objc -prefix=  github.com/exis-io/core/androidMantle
//
// File is generated by gobind. Do not edit.

#ifndef __ Mantle_H__
#define __ Mantle_H__

#include <Foundation/Foundation.h>

@class  MantleDomain;

@interface  MantleDomain : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (void)call:(NSString*)endpoint cb:(NSString*)cb eb:(NSString*)eb args:(NSString*)args;
- (void)callExpects:(NSString*)cb types:(NSString*)types;
- (void)join:(NSString*)cb eb:(NSString*)eb;
- (void)leave;
- ( MantleDomain*)linkDomain:(NSString*)name;
- (void)publish:(NSString*)endpoint cb:(NSString*)cb eb:(NSString*)eb args:(NSString*)args;
- (NSString*)receive;
- (void)register:(NSString*)endpoint cb:(NSString*)cb eb:(NSString*)eb fn:(NSString*)fn types:(NSString*)types;
- ( MantleDomain*)subdomain:(NSString*)name;
- (void)subscribe:(NSString*)endpoint cb:(NSString*)cb eb:(NSString*)eb fn:(NSString*)fn types:(NSString*)types;
- (void)unregister:(NSString*)endpoint cb:(NSString*)cb eb:(NSString*)eb;
- (void)unsubscribe:(NSString*)endpoint cb:(NSString*)cb eb:(NSString*)eb;
- (void)yield:(NSString*)request args:(NSString*)args;
- (void)yieldError:(NSString*)request etype:(NSString*)etype args:(NSString*)args;
@end

FOUNDATION_EXPORT void  MantleApplication(NSString* s);

FOUNDATION_EXPORT void  MantleDebug(NSString* s);

FOUNDATION_EXPORT void  MantleError(NSString* s);

FOUNDATION_EXPORT void  MantleGetBytes(NSData* bit);

FOUNDATION_EXPORT NSString*  MantleHello(NSString* name);

FOUNDATION_EXPORT void  MantleInfo(NSString* s);

FOUNDATION_EXPORT  MantleDomain*  MantleNewDomain(NSString* name);

FOUNDATION_EXPORT void  MantleSetCuminLoose();

FOUNDATION_EXPORT void  MantleSetCuminOff();

FOUNDATION_EXPORT void  MantleSetCuminStrict();

FOUNDATION_EXPORT void  MantleSetFabric(NSString* url);

FOUNDATION_EXPORT void  MantleSetFabricDev();

FOUNDATION_EXPORT void  MantleSetFabricLocal();

FOUNDATION_EXPORT void  MantleSetFabricProduction();

FOUNDATION_EXPORT void  MantleSetFabricSandbox();

FOUNDATION_EXPORT void  MantleSetLogLevelApp();

FOUNDATION_EXPORT void  MantleSetLogLevelDebug();

FOUNDATION_EXPORT void  MantleSetLogLevelErr();

FOUNDATION_EXPORT void  MantleSetLogLevelInfo();

FOUNDATION_EXPORT void  MantleSetLogLevelOff();

FOUNDATION_EXPORT void  MantleSetLogLevelWarn();

FOUNDATION_EXPORT void  MantleSetRegistrar(NSString* url);

FOUNDATION_EXPORT void  MantleWarn(NSString* s);

#endif
